DROP VIEW IF EXISTS vw_SLSX_HangHoa
GO
CREATE VIEW vw_SLSX_HangHoa AS
SELECT K.MaHH, TenHH, SlSanXuat
FROM KHSX K
         LEFT JOIN Hang_Hoa HH ON HH.MaHH = K.MaHH
WHERE NamThang = '200504'
  AND K.MaHH = 'G001'
GO

DROP VIEW IF EXISTS vw_HangHoa_2005
GO
CREATE VIEW vw_HangHoa_2005 AS
SELECT DISTINCT K.MaHH, TenHH
FROM KHSX K
         LEFT JOIN Hang_Hoa HH ON K.MaHH = HH.MaHH
WHERE NamThang LIKE '2005%'
GO

DROP VIEW IF EXISTS vw_HangHoa_GT80000
GO
CREATE VIEW vw_HangHoa_GT80000 AS
SELECT HH.MaHH, TenHH, TenNVL, DonGia
FROM NVL N
         LEFT JOIN Dinh_Muc D ON D.MaNVL = N.MaNVL
         LEFT JOIN Hang_Hoa HH ON D.MaHH = HH.MaHH
WHERE DonGia >= 80000
GO


DROP VIEW IF EXISTS vw_HangHoa_DM03
GO
CREATE VIEW vw_HangHoa_DM03 AS
SELECT HH.MaHH, TenHH, TenNVL, SlDinhMuc
FROM NVL N
         LEFT JOIN Dinh_Muc D ON D.MaNVL = N.MaNVL
         LEFT JOIN Hang_Hoa HH ON D.MaHH = HH.MaHH
WHERE SlDinhMuc = 0.3
GO

DROP VIEW IF EXISTS vw_HangHoa_Giay
GO
CREATE VIEW vw_HangHoa_Giay AS
SELECT MaHH, TenHH
FROM Hang_Hoa
WHERE TenHH LIKE N'Giày%'
GO

DROP VIEW IF EXISTS vw_HangHoa_GachDuoi
GO
CREATE VIEW vw_HangHoa_GachDuoi AS
SELECT MaHH, TenHH
FROM Hang_Hoa
WHERE TenHH LIKE N'%_%'
GO

DROP VIEW IF EXISTS vw_HangHoa_NOTSX
GO
CREATE VIEW vw_HangHoa_NOTSX AS
SELECT Hang_Hoa.MaHH, TenHH
FROM Hang_Hoa
         LEFT JOIN KHSX ON Hang_Hoa.MaHH = KHSX.MaHH
WHERE KHSX.MaHH IS NULL
GO





