SELECT *
FROM DMSV

SELECT MaSV, UPPER(TenSV) AS TenSv, (IIF(Nam = 0, N'Nữ', 'Nam')) AS GioiTinh
FROM DMSV
ORDER BY TenSV

SELECT TOP 2 TenSv, (IIF(Nam = 0, N'Nữ', 'Nam')) AS GioiTinh
FROM DMSV

SELECT TOP 50 PERCENT *
FROM DMSV

SELECT TenKH, TenSV
FROM DMSV
         LEFT JOIN DMKHOA ON DMSV.MaKH = DMKHOA.MaKH
ORDER BY TenKH

SELECT TenSV, TenKH, TenMH, Diem
FROM DMSV
         LEFT JOIN DMKHOA ON DMSV.MaKH = DMKHOA.MaKH
         LEFT JOIN KETQUA ON DMSV.MaSV = KETQUA.MaSV
         LEFT JOIN DMMH ON KETQUA.MaMH = DMMH.MaMH

SELECT DMKHOA.MaKH, TenKH, COUNT(MaSV) AS SoSv
FROM DMKHOA
         LEFT JOIN DMSV ON DMKHOA.MaKH = DMSV.MaKH
GROUP BY DMKHOA.MaKH, TenKH

DECLARE @MaMonHoc CHAR(2) = '05'
SELECT DMSV.MaSV, TenSV, Diem AS DiemCao
FROM DMSV
         LEFT JOIN KETQUA ON DMSV.MaSV = KETQUA.MaSV
WHERE Diem = (SELECT MAX(Diem) FROM KETQUA WHERE KETQUA.MaMH = @MaMonHoc)
  AND KETQUA.MaMH = @MaMonHoc